name: Build library and run tests
on:
  push:
    branches: [ master, devel ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    container: 
      image: bausma/mbed-dev-env:latest
      options: --user root
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Checkout Frankly Bootloader Library
        run: |
          mkdir -p ../frankly-bootloader
          git clone https://github.com/franc0r/frankly-bootloader.git ../frankly-bootloader
          (cd ../frankly-bootloader && git checkout devel)
      - name: Build STM NUCLEO-G491RB Bootloader Example
        run: |
          cd boards/stm_nucleo_g431rb/franklyboot_g431rb
          make
      - name: Build STM NUCLEO-G491RB App Example
        run: |
          cd boards/stm_nucleo_g431rb/example_app_g431rb
          make
      - name: Build STM NUCLEO-F303K8 Bootloader Example
        run: |
          cd boards/stm_nucleo_f303k8/franklyboot_f303k8
          make
      - name: Build STM NUCLEO-F303K8 App Example
        run: |
          cd boards/stm_nucleo_f303k8/example_app_f303k8
          make
      - name: Build EDUART L431KB CAN Bootloader Example
        run: |
          cd boards/eduart_l431kb_can/franklyboot_eduart_l431kb
          make
#      - uses: actions/checkout@v3
#      - name: Build STM NUCLEO_G491RB Example
#        run: |
#          echo $(pwd)
#          ls
#          cd stm_nucleo_g431rb
#          make
